import { Metadata } from "next";
import { notFound } from "next/navigation";
import ClientPage from "./page.client";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Home = async () => {
  try {
    return <ClientPage />;
  } catch (e) {
    notFound();
  }
};

export default Home;
