import BottomTab from "@/components/BottomTab";
import ReactQueryProvider from "@/components/provider/ReactQueryProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Druid Diary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div className="flex justify-center items-center min-h-screen bg-gray-100">
            <div className="w-full min-w-sm max-w-lg min-h-screen bg-white pb-14">
              {children}
            </div>
            <BottomTab />
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
