import BottomTab from "@/components/BottomTab";
import ReactQueryProvider from "@/components/provider/ReactQueryProvider";
import type { Metadata } from "next";

// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.ttf",
  variable: "--pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Druid Diary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <ReactQueryProvider>
          <section className="flex justify-center items-center min-h-screen bg-gray-100">
            <div className="w-full min-w-sm max-w-lg min-h-screen bg-white pb-14">
              {children}
            </div>
            <BottomTab />
          </section>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
